version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "14:00"
      timezone: UTC
    labels:
      - dependencies
      - rust
      - security
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "14:00"
      timezone: UTC
    labels:
      - dependencies
      - javascript
      - security
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: "/apps/desktop/ui"
    schedule:
      interval: weekly
      day: monday
      time: "14:00"
      timezone: UTC
    labels:
      - dependencies
      - javascript
      - security
    open-pull-requests-limit: 10
