[package]
name = "kc_extract"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
kc_core = { path = "../kc_core" }
regex = "1.12"
serde.workspace = true
serde_json.workspace = true
